baseurl = "/"
languageCode = "en-US"
title = "Chionesu By Design"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

#[permalinks]
#    post = "/:year/:month/:day/:slug/"

#[[menu.main]]
#    name = "About"
#    url = "/about/"
#[[menu.main]]
#    name = "GitHub"
#    url = "https://github.com/rstudio/blogdown"
#[[menu.main]]
#    name = "Twitter"
#    url = "https://twitter.com/rstudio"
[[menu.main]]
    name = "Articles"
    url = "/post/"
    weight = 10
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/chionesu-george-1067b122/"
    weight = 40
[[menu.main]]
    name = "R Packages"
    url = "/r-pkgs/"
    weight = 20
[[menu.main]]
    name = "Data Projects"
    url = "/data-projects/"
    weight = 30

[params]
    description = "Chionesu's digital home"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = false

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'