baseurl = "/"
publishDir = "docs"

title = "Chionesu By Design"
theme = "hugo-lithium"
languageCode = "en-US"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.qmd$", "_cache$"]
enableGitInfo = true

[[menu.main]]
    name = "Articles"
    url = "/post/"
    weight = 10
[[menu.main]] 
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/chionesu-george-1067b122/"
    weight = 40
[[menu.main]]
    name = "R Packages"
    url = "/r-pkgs/"
    weight = 20
[[menu.main]]
    name = "Data Projects"
    url = "/data_projects/"
    weight = 30

[params]
  description = "Chionesu's digital home"
  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion = "2.7.5"
  highlightjsVersion = "9.12.0"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"
  dateForm = "Jan 2020"
  tocMinWordCount = 1000
  
  # path to the favicon, under "static"
  favicon = "favicon.ico"

  [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = false
#  [markup.tableOfContents]
#    endLevel = 3
#    ordered = false
#    startLevel = 2
  
[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
