baseurl: /
title: Chionesu By Design
languageCode: en-us
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$

permalinks:
  posts: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: Articles
      url: /post/
      weight: 10
    - name: LinkedIn
      url: https://www.linkedin.com/in/chionesu-george-1067b122/
      weight: 40
    - name: R Packages
      url: /r-pkgs/
      weight: 20
    - name: Data Projects
      url: /data-projects/
      weight: 30

params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: The digital home of Chionesu George
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  favicon: favicon.ico
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
  css: markdown.css
  
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
